FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl  nano \
    && rm -rf /var/lib/apt/lists/*

RUN curl -Ls https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN mkdir -p /app && mkdir -p /app/caregiver


COPY caregiver/src /app/caregiver/src/
COPY caregiver/static /app/caregiver/static/
COPY caregiver/README.md \
    caregiver/pyproject.toml \
    caregiver/uv.lock \
    /app/caregiver/

WORKDIR /app/caregiver

RUN uv sync

CMD ["uv", "run", "uvicorn", "caregiver.main:app", "--host", "0.0.0.0", "--port", "8000"]
